name: CI - Dev Branch

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc gcsfs

    - name: Configure GCP Credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure DVC
      run: |
        dvc init --no-scm
        dvc remote add -d myremote gs://mlops-iris-week2-graded-unique-shubhamg/week_2
        dvc pull

    - name: Run tests with pytest
      run: |
        pytest tests/ -v --tb=short

    - name: Install CML
      run: |
        pip install "cml>=0.19.0"

    - name: Create CML Report
      run: |
        echo "## Test Results 📊" >> report.md
        echo "### 🧪 Pytest Summary" >> report.md
        echo "\`\`\`" >> report.md
        pytest tests/ -v >> report.md 2>&1 || true
        echo "\`\`\`" >> report.md
        echo "### 📈 Confusion Matrix" >> report.md
        echo "\`\`\`" >> report.md
        python -c "
        import pandas as pd
        import joblib
        from get_data import download_data
        import train
        from sklearn.metrics import confusion_matrix
        
        download_data('v1')
        train.main()
        data = pd.read_csv('data/data.csv')
        model = joblib.load('model.joblib')
        X = data.drop('species', axis=1)
        y = data['species']
        predictions = model.predict(X)
        cm = confusion_matrix(y, predictions)
        print('Actual \\\\ Predicted  setosa  versicolor  virginica')
        species = ['setosa', 'versicolor', 'virginica']
        for i, actual in enumerate(species):
            print(f'{actual:12}      {cm[i]}')
        " >> report.md 2>&1
        echo "\`\`\`" >> report.md
        
        cml comment create report.md
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}